### ISSUE TITLE
Red underline over all code in class

### ISSUE THREAD

**Issue by SendiMyrkr** [nette-intellij/intellij-nette-tester#36]
I've got it sometime after code changes. I see message "Test case is not run" even i have someting like
"(new SomeClassTest())->run();" at end of file. I have Windows, just for case.

**Comment by jiripudil** [comment]
Yes, this inspection seems to be buggy. I'll probably drop it altogether rather than trying to find out what's wrong. It doesn't add that much value anyway, because Tester already gives a hint if the test doesn't execute any assertions

**Comment by SendiMyrkr** [comment]
Agreed, it's super-annoying with minimal value. But do you get this message(missing assertation) even if TestCase is not actually run?

**Comment by jiripudil** [comment]
Yes. Provided that Tester recognizes the file as a test (and there *is* a *working* inspection for that 😉), it marks the test as failed if it does not execute any assertions. And, trivially, when the contained TestCase is not run, it executes no assertions.
